import request from '@/utils/request'
export function listCompetition(q){return request({url:'/api/v1/competitions/list',method:'get',params:q})}
export function getCompetition(id){return request({url:'/api/v1/competitions/'+id,method:'get'})}
export function addCompetition(d){return request({url:'/api/v1/competitions',method:'post',data:d})}
export function updateCompetition(d){return request({url:'/api/v1/competitions',method:'put',data:d})}
export function changeStatus(id,status){return request({url:'/api/v1/competitions/'+id+'/status',method:'put',data:{status}})}
export function addStage(d){return request({url:'/api/v1/competitions/stages',method:'post',data:d})}
export function removeStage(id){return request({url:'/api/v1/competitions/stages/'+id,method:'delete'})}
export function addParticipants(d){return request({url:'/api/v1/competitions/participants',method:'post',data:d})}
export function removeParticipant(cid,uid){return request({url:'/api/v1/competitions/'+cid+'/participants/'+uid,method:'delete'})}
export function delCompetition(id){return request({url:'/api/v1/competitions/'+id,method:'delete'})}
